services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_USER=board
      - MYSQL_PASSWORD=board
      - MYSQL_DATABASE=board
      - MYSQL_ROOT_PASSWORD=board